from datetime import datetime, timedelta

from app.actions.idempotency import incident_marker
from app.agent.hypotheses import CATALOG
from app.agent.types import HypothesisView
from app.db.models import EvidenceItem

DISPLAY = {"slack": "Slack", "github": "GitHub", "sheets": "Sheets"}
REPORT_HEADER = "## Surge incident report"
EVIDENCE_HEADER = "### Supporting evidence"


def find_existing_incident(issues: list[dict], fingerprint: str, kind: str, onset: datetime) -> dict | None:
    marker = incident_marker(fingerprint)
    open_issues = [i for i in issues if i.get("state") == "open"]
    for issue in open_issues:
        if marker in (issue.get("body") or ""):
            return issue
    keywords = CATALOG[kind].keywords
    for issue in open_issues:
        text = f"{issue.get('title', '')} {issue.get('body') or ''}".lower()
        labels = {str(l).lower() for l in issue.get("labels", [])}
        created = issue.get("created_at")
        recent = created is None or (onset - timedelta(hours=6) <= created <= onset + timedelta(hours=48))
        if "incident" in labels and recent and any(k in text for k in keywords):
            return issue
    return None


def _evidence_line(e: EvidenceItem, strength: str | None = None) -> str:
    link = f" ([source]({e.url}))" if e.url else ""
    suffix = f" — {strength}" if strength else ""
    return f"- **[{DISPLAY.get(e.source_app, e.source_app)}]** {e.title}{suffix}{link} `{e.id}`"


def render_findings(
    *,
    investigation_id: str,
    synthesis: dict,
    selected: HypothesisView,
    views: list[HypothesisView],
    evidence: dict[str, EvidenceItem],
    marker_lines: list[str],
) -> str:
    breakdown = synthesis.get("confidence_breakdown") or {}
    lines = [
        REPORT_HEADER,
        "",
        f"**Strongest supported hypothesis:** {selected.statement}",
        f"**Confidence:** {synthesis['confidence']:.2f} (evidence-weighted belief, not proof; "
        f"posterior {breakdown.get('posterior', 0):.2f} × source coverage {breakdown.get('coverage_factor', 1):.2f})",
    ]
    anomaly_id = synthesis.get("anomaly_evidence_id")
    if anomaly_id in evidence:
        lines.append(f"**Detected change:** {evidence[anomaly_id].title}")
    lines += ["", EVIDENCE_HEADER]
    for link in selected.supporting[:8]:
        if link.evidence_id in evidence:
            lines.append(_evidence_line(evidence[link.evidence_id], link.strength))
    if selected.contradicting:
        lines += ["", "### Contradicting evidence"]
        for link in selected.contradicting[:5]:
            if link.evidence_id in evidence:
                lines.append(_evidence_line(evidence[link.evidence_id], link.strength))
    alternatives = [v for v in views if v.id != selected.id]
    if alternatives:
        lines += ["", "### Alternatives considered"]
        for alt in synthesis.get("alternatives_considered", []):
            lines.append(f"- {alt['label']} — {alt['status']} (confidence {alt['confidence']:.2f}): {alt['reason']}")
    if synthesis.get("uncertainties"):
        lines += ["", "### Uncertainty"] + [f"- {u}" for u in synthesis["uncertainties"]]

    change = next(
        (evidence[l.evidence_id] for l in selected.supporting if l.evidence_id in evidence and evidence[l.evidence_id].source_type == "code_change"),
        None,
    )
    lines += ["", "### Suggested next steps"]
    if change:
        meta = change.source_metadata or {}
        files = ", ".join((meta.get("files") or [])[:4])
        lines.append(f"- {CATALOG[selected.kind].team.capitalize()} team: review `{meta.get('ref')}` ({files}) and decide whether to roll back.")
    lines.append("- Confirm against production error logs before taking irreversible remediation.")
    lines += [
        "",
        "---",
        f"_Generated by Surge investigation `{investigation_id}`. Every item above links to a stored evidence record._",
        "",
        *[f"<!-- {m} -->" for m in marker_lines],
    ]
    return "\n".join(lines)


def issue_title(synthesis: dict, selected: HypothesisView, metric_label: str, evidence: dict[str, EvidenceItem]) -> str:
    anomaly = synthesis.get("anomaly") or {}
    drop = abs(anomaly.get("relative_change") or 0) * 100
    ref = next(
        (
            (evidence[l.evidence_id].source_metadata or {}).get("ref")
            for l in selected.supporting
            if l.evidence_id in evidence and evidence[l.evidence_id].source_type in ("code_change", "deployment")
        ),
        None,
    )
    title = f"[Surge] {metric_label.capitalize()} down {drop:.0f}% — suspected {selected.label.lower()}"
    return f"{title} ({ref})" if ref else title
